data:

  index:
    train: "data/index/train.csv"
    val: "data/index/val.csv"
    test: "data/index/test.csv"

  image_size: [128, 128]
  n_classes: 3
  in_channels: 3

model: "MobileNetV3S"  # One of ["EffNetV2S", "MobileNetV3S"]

training:

  learning_rate: 0.00575
  batch_size: 128
  use_augmentations: true
  use_early_stopping: true
  early_stopping_kwargs:
    monitor: "val_loss"
    mode: min
    min_delta: 0
    patience: 10
    verbose: true

  trainer_kwargs:
    accelerator: "gpu"
    devices: 1
    max_epochs: 100
    precision: 32
    enable_checkpointing: true
    auto_lr_find: true

  num_workers: 8  # Number of workers for the dataloaders
  pin_memory: true  # Whether to pin memory in the dataloaders

eval:
  batch_size: 128
  ckpt_path: "/home/scronberg/Documents/GitHub/shoe-sandal-boot-clf-pytorch/lightning_logs/version_33/checkpoints/epoch=47-step=18000.ckpt"  # Path to model checkpoint

seed: 42
