data:

  index:
    train: "data/index/train.csv"
    val: "data/index/val.csv"
    test: "data/index/test.csv"

  image_size: [240, 240]
  n_classes: 3
  in_channels: 3

model: "MobileNetV3S"  # One of ["EffNetV2S", "MobileNetV3S"]

training:

  learning_rate: 0.0001
  batch_size: 32
  use_augmentations: true
  use_early_stopping: true
  early_stopping_kwargs:
    monitor: "val_loss"
    mode: min
    min_delta: 0
    patience: 10
    verbose: true

  trainer_kwargs:
    accelerator: "gpu"
    devices: 1
    max_epochs: 100
    precision: 16
    enable_checkpointing: true

  num_workers: 8  # Number of workers for the dataloaders
  pin_memory: bool  # Whether to pin memory in the dataloaders

seed: 42
