data:

  root_data_dir: "."  # Absolute or relative path to the parent directory of data/
  index:
    train: "data/index/train.csv"
    val: "data/index/val.csv"
    test: "data/index/test.csv"

  image_size: [240, 240]
  n_classes: 3
  in_channels: 3

model: "MobileNetV3S"  # One of ["EffNetV2S", "MobileNetV3S"]

training:

  learning_rate: 3e-4  # Karpathy constant :)
  batch_size: 32
  use_augmentations: true
  use_early_stopping: true
  early_stopping_kwargs:
    monitor: "val_loss"
    mode: min
    min_delta: 0
    patience: 10
    verbose: true

  # Arguments for the Lightning Trainer class
  trainer_kwargs:
    accelerator: "gpu"
    devices: 1
    max_epochs: 100
    precision: 32  # Floating point precision
    enable_checkpointing: true

  # Arguments for the training dataloader
  dataloader_kwargs:
    batch_size: 32
    shuffle: true
    num_workers: 8
    pin_memory: false


  num_workers: 8  # Number of workers for the dataloaders
  pin_memory: bool  # Whether to pin memory in the dataloaders

eval:
  ckpt_path: "lightning_logs/version_4/checkpoints/epoch=3-step=1500.ckpt"  # Path to model checkpoint

  # Arguments for the validation/test dataloaders
  dataloader_kwargs:
    batch_size: 512
    shuffle: false
    num_workers: 8
    pin_memory: false

seed: 42
